package vn.ai.lich.tv
import java.time.LocalDate
import java.time.temporal.ChronoUnit

data class TVDayDetail(val canChiDay:String,val canChiMonth:String,val canChiYear:String,val napAm:String,val tietKhi:String,val truc:String,val trucNote:String,val tu:String,val tuNote:String)
object TVDayDetails{
 private val chi=listOf("Tý","Sửu","Dần","Mão","Thìn","Tỵ","Ngọ","Mùi","Thân","Dậu","Tuất","Hợi")
 private val truc=listOf("Kiến","Trừ","Mãn","Bình","Định","Chấp","Phá","Nguy","Thành","Thu","Khai","Bế")
 private val trucNotes=listOf("Khởi lập, bắt đầu việc mới.","Loại bỏ điều cũ, sửa sang, thanh lọc.","Việc tiến tới đầy đủ, viên mãn.","Thiên về cân bằng và ổn định.","Thiên về xác lập, ổn định.","Thiên về duy trì, giữ vững việc đang có.","Thiên về phá bỏ; thận trọng với việc trọng đại.","Có tính bất ổn; nên thận trọng.","Thiên về hoàn thành, thành tựu.","Thiên về thu nhận, thu hoạch.","Thiên về mở ra, khai mở.","Thiên về đóng lại; không thuận cho khởi sự lớn.")
 private val tus=listOf("Giác","Cang","Đê","Phòng","Tâm","Vĩ","Cơ","Đẩu","Ngưu","Nữ","Hư","Nguy","Thất","Bích","Khuê","Lâu","Vị","Mão","Tất","Chủy","Sâm","Tỉnh","Quỷ","Liễu","Tinh","Trương","Dực","Chẩn")
 private val tuNotes=listOf("Thuận thi cử, cầu danh, cưới hỏi; tránh mai táng.","Thận trọng việc lớn, nhất là cưới hỏi và mai táng.","Không thuận việc lớn; thiên về cầu an, lễ bái.","Thuận tài sản, động thổ, cưới hỏi.","Tránh khai trương, hôn sự, kiện tụng và chi xuất lớn.","Thuận xuất hành, khai trương, ký kết và xây dựng.","Thuận làm nhà, mở cửa hàng, khai trương.","Thuận hôn sự, sinh nở, trồng trọt, chăn nuôi.","Tránh cưới hỏi, khai trương và việc tài chính lớn.","Tránh vay mượn, ký kết, nhậm chức và hôn sự.","Không thuận hôn sự và việc trọng đại.","Tránh khai trương, xây nhà và động thổ.","Thuận kinh doanh, khai trương, xây dựng, hôn sự.","Cát cho hôn sự, kinh doanh, xây nhà, động thổ.","Bất lợi cưới hỏi, kinh doanh; có việc lại thuận xây dựng.","Thuận nhậm chức, hôn thú, khai trương.","Thiên về cát vượng, gia đạo và kinh doanh.","Thận trọng xây dựng, hôn sự và kinh doanh.","Thuận xây nhà, động thổ, cưới hỏi và tài chính.","Tránh nhậm chức, cho vay và ký kết hợp đồng.","Thuận hôn sự, kinh doanh, ký kết, xuất hành.","Thuận làm nhà, công việc, thi cử và hôn sự; tránh an táng.","Không thuận hỷ sự, xây dựng; có hệ dùng cho mai táng.","Không thuận xuất hành và việc tiền hàng lớn.","Tránh cưới hỏi; có thể dùng cho một số việc xây dựng.","Cát tú; thuận tạo tác, hôn sự và việc vui.","Hung tú; thận trọng hôn sự và việc trọng đại.","Thuận nhậm chức, thi cử, kinh doanh, hôn sự.")
 private val monthChi=mapOf("Lập Xuân" to "Dần","Vũ Thủy" to "Dần","Kinh Trập" to "Mão","Xuân Phân" to "Mão","Thanh Minh" to "Thìn","Cốc Vũ" to "Thìn","Lập Hạ" to "Tỵ","Tiểu Mãn" to "Tỵ","Mang Chủng" to "Ngọ","Hạ Chí" to "Ngọ","Tiểu Thử" to "Mùi","Đại Thử" to "Mùi","Lập Thu" to "Thân","Xử Thử" to "Thân","Bạch Lộ" to "Dậu","Thu Phân" to "Dậu","Hàn Lộ" to "Tuất","Sương Giáng" to "Tuất","Lập Đông" to "Hợi","Tiểu Tuyết" to "Hợi","Đại Tuyết" to "Tý","Đông Chí" to "Tý","Tiểu Hàn" to "Sửu","Đại Hàn" to "Sửu")
 fun forDate(d:LocalDate,l:LunarDate):TVDayDetail{ val tk=VietnameseLunar.tietKhi(d); val dc=VietnameseLunar.dayChi(l.julianDay); val mc=monthChi[tk]?:"Dần"; val ti=(chi.indexOf(dc)-chi.indexOf(mc)).mod(12); val off=ChronoUnit.DAYS.between(LocalDate.of(2026,4,15),d).toInt(); val ui=(13+off).mod(28); return TVDayDetail(VietnameseLunar.dayCanChi(l.julianDay),VietnameseLunar.monthCanChi(l.month,l.year),VietnameseLunar.yearCanChi(l.year),VietnameseLunar.napAm(l.julianDay),tk,truc[ti],trucNotes[ti],tus[ui],tuNotes[ui]) }
}
